### ISSUE TITLE
Edit QField Variables on project open as example plugin

### ISSUE THREAD

**Issue by cratcliff** [opengisch/qfield-template-plugin#1]
I have been using qfield project variables like  `operator`, `project`, `location`, `site`, `activity` that can then be assigned to new features across multiple layers while editing. I know how to manually achieve this via __settings/Variables_; which users forget to update, or QGIS Project variables; that can't be edited from within QField. 

My idea was to create a Qfield plugin to prompt a user to update these variables when a project is opened but I lack the experience with QML and Javascript.

There are already several discussions on this topic ( https://github.com/opengisch/QField/issues/4374, https://github.com/opengisch/QField/issues/1814) but I thought that this could make a really good plugin and useful template highlighting the possibilities mentioned in the help docs.

**Comment by nirvn** [comment]
@cratcliff , great idea. The functionality for plugins to do so has been added here (https://github.com/opengisch/QField/pull/5402) and should be available in QField's next point release.

As for the plugin itself, hoping you'll amaze us all by learning a bit of javascript and QML :)

The actual functions you'd use (once the PR is merged and part of an official release) would be `ExpressionContextUtils.setGlobalVariable('key', 'value')` or `ExpressionContextUtils.setProjectVariable(qgisProject, 'key', 'value')`.

**Comment by m-kuhn** [comment]
@cratcliff congrats you might be the first one to deserve one of these.
Are you at FOSS4G next week or do you want to send me your postal address?

<img width="310" alt="image (2)" src="https://github.com/opengisch/qfield-template-plugin/assets/588407/59ce5336-4aec-4c82-aa21-190cdb84a46a">

**Comment by nirvn** [comment]
@cratcliff , the API was added into the latest QField point release (3.3.6), let us know if you come up with a plugin!
